"""
SQL Validation and Security Guardrail Module
============================================
Provides rigorous structural, syntactic, relational, and security validation for SQL
queries generated by natural-language systems.

Enforces read-only safety, table whitelisting, controlled relational join key enforcement,
and protection against injection or destructive modifications.
"""

import re
import sqlite3
from typing import Any, Dict, List, Optional, Set

from src.talk_to_data.schema import (
    ALLOWED_TABLES,
    TABLE_NAME,
    get_all_allowed_columns,
    get_allowed_columns
)


# Disallowed SQL keywords that perform data modification, DDL, or database inspection
FORBIDDEN_KEYWORDS: Set[str] = {
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "TRUNCATE",
    "REPLACE", "CREATE", "ATTACH", "DETACH", "PRAGMA", "VACUUM",
    "REINDEX", "EXEC", "EXECUTE", "GRANT", "REVOKE", "SAVEPOINT",
    "RELEASE", "ROLLBACK", "COMMIT", "BEGIN", "TRANSACTION", "LOCK"
}

# Forbidden internal SQLite tables and metadata views
FORBIDDEN_TABLES: Set[str] = {
    "SQLITE_MASTER", "SQLITE_SCHEMA", "SQLITE_TEMP_MASTER",
    "SQLITE_TEMP_SCHEMA", "SQLITE_SEQUENCE", "SQLITE_STAT1", "SQLITE_STAT4"
}

# Valid join key across all relational analytical tables
VALID_JOIN_KEY = "sk_id_curr"


def strip_sql_comments(sql_query: str) -> str:
    """Remove line comments (-- ...) and block comments (/* ... */)."""
    clean = re.sub(r"--.*$", "", sql_query, flags=re.MULTILINE)
    clean = re.sub(r"/\*.*?\*/", "", clean, flags=re.DOTALL)
    return clean.strip()


def validate_join_clauses(sql_query: str) -> Dict[str, Any]:
    """
    Validate that multi-table JOINs adhere to the approved join whitelist:
    - Tables must be in ALLOWED_TABLES
    - Joins must be keyed on sk_id_curr (e.g., ON a.sk_id_curr = b.sk_id_curr or USING (sk_id_curr))
    """
    if not re.search(r"\bJOIN\b", sql_query, re.IGNORECASE):
        return {"valid": True, "reason": "No JOIN clauses."}

    # Split by JOIN keywords to inspect each joined table and its condition
    join_blocks = re.split(
        r"\b(?:INNER|LEFT|RIGHT|FULL|CROSS|NATURAL)?\s*JOIN\s+",
        sql_query,
        flags=re.IGNORECASE
    )

    for block in join_blocks[1:]:
        tokens = block.strip().split()
        if not tokens:
            return {"valid": False, "reason": "Malformed JOIN clause."}
        table_name = tokens[0].lower().rstrip(",")
        if table_name not in ALLOWED_TABLES:
            return {
                "valid": False,
                "reason": f"Unauthorized table in JOIN: '{table_name}'. Only approved tables {sorted(list(ALLOWED_TABLES))} are permitted."
            }

        # Extract clause text up to subsequent SQL keywords
        clause_text = re.split(
            r"\b(?:WHERE|GROUP\s+BY|HAVING|ORDER\s+BY|LIMIT|WINDOW)\b",
            block,
            flags=re.IGNORECASE
        )[0]

        using_match = re.search(r"\bUSING\s*\(\s*([A-Za-z0-9_]+)\s*\)", clause_text, re.IGNORECASE)
        on_match = re.search(r"\bON\s+(.+)$", clause_text, re.IGNORECASE | re.DOTALL)

        if using_match:
            using_col = using_match.group(1).lower()
            if using_col != VALID_JOIN_KEY:
                return {
                    "valid": False,
                    "reason": f"Invalid join key in USING clause: '{using_col}'. Relational joins must use '{VALID_JOIN_KEY}'."
                }
        elif on_match:
            on_cond = on_match.group(1).strip().rstrip(";")
            if VALID_JOIN_KEY not in on_cond.lower():
                return {
                    "valid": False,
                    "reason": f"Invalid join condition '{on_cond}'. Relational joins must be keyed on '{VALID_JOIN_KEY}'."
                }
            # Check forbidden keywords in ON condition
            on_tokens = set(re.findall(r"\b[A-Za-z_]+\b", on_cond.upper()))
            if on_tokens.intersection(FORBIDDEN_KEYWORDS):
                return {
                    "valid": False,
                    "reason": f"Forbidden keyword in JOIN condition: {sorted(list(on_tokens.intersection(FORBIDDEN_KEYWORDS)))}"
                }
        elif "NATURAL" in sql_query.upper():
            pass
        else:
            return {
                "valid": False,
                "reason": f"JOIN on table '{table_name}' is missing an explicit ON or USING condition."
            }

    return {"valid": True, "reason": "Join clauses valid."}


def validate_sql(
    sql_query: str,
    db_path: Optional[str] = None
) -> Dict[str, Any]:
    """
    Perform multi-layer validation of generated SQL statements:
    1. Single-statement validation (no semicolon chaining).
    2. Read-only token audit (no mutation/DDL/PRAGMA keywords).
    3. Whitelist table verification (only approved analytics/relational tables).
    4. Controlled relational join key verification.
    5. SQLite syntax / dry-run compilation test.

    Args:
        sql_query: Raw generated SQL string.
        db_path: Optional path to an existing SQLite database for dry-run verification.

    Returns:
        Dict with keys:
            - 'valid' (bool)
            - 'reason' (str)
            - 'sanitized_sql' (Optional[str])
            - 'tables_used' (List[str])
    """
    if not sql_query or not isinstance(sql_query, str):
        return {
            "valid": False,
            "reason": "Query is empty or not a valid string.",
            "sanitized_sql": None,
            "tables_used": []
        }

    # Step 1: Clean comments and whitespace
    clean_sql = strip_sql_comments(sql_query)
    clean_sql = clean_sql.strip()

    # Step 2: Remove trailing semicolon for single statement checking
    if clean_sql.endswith(";"):
        clean_sql = clean_sql[:-1].strip()

    if not clean_sql:
        return {
            "valid": False,
            "reason": "Query contains no executable SQL content.",
            "sanitized_sql": None,
            "tables_used": []
        }

    # Step 3: Reject multiple statement chaining (internal semicolons)
    if ";" in clean_sql:
        return {
            "valid": False,
            "reason": "Multi-statement queries or chained semicolons are prohibited.",
            "sanitized_sql": None,
            "tables_used": []
        }

    # Step 4: Statement must begin with SELECT or WITH (for CTEs)
    first_token = clean_sql.split()[0].upper()
    if first_token not in {"SELECT", "WITH"}:
        return {
            "valid": False,
            "reason": f"Only SELECT queries are permitted. Query began with '{first_token}'.",
            "sanitized_sql": None,
            "tables_used": []
        }

    # Step 5: Extract all word tokens and check for forbidden keywords
    tokens = set(re.findall(r"\b[A-Za-z_]+\b", clean_sql.upper()))
    
    forbidden_found = tokens.intersection(FORBIDDEN_KEYWORDS)
    if forbidden_found:
        return {
            "valid": False,
            "reason": f"Forbidden SQL keywords detected: {sorted(list(forbidden_found))}",
            "sanitized_sql": None,
            "tables_used": []
        }

    # Step 6: Check for forbidden internal table access
    forbidden_tables_found = tokens.intersection(FORBIDDEN_TABLES)
    if forbidden_tables_found:
        return {
            "valid": False,
            "reason": f"Access to internal SQLite tables is prohibited: {sorted(list(forbidden_tables_found))}",
            "sanitized_sql": None,
            "tables_used": []
        }

    # Step 7: Table Name Whitelist Check
    table_pattern = r"(?:FROM|JOIN)\s+([A-Za-z0-9_]+)"
    referenced_tables = [t.lower() for t in re.findall(table_pattern, clean_sql, flags=re.IGNORECASE)]

    if not referenced_tables:
        if not any(t.upper() in tokens for t in ALLOWED_TABLES):
            return {
                "valid": False,
                "reason": f"Query does not reference an approved analytics table. Allowed: {sorted(list(ALLOWED_TABLES))}.",
                "sanitized_sql": None,
                "tables_used": []
            }
        referenced_tables = [TABLE_NAME]

    unauthorized_tables = set(referenced_tables) - ALLOWED_TABLES
    if unauthorized_tables:
        return {
            "valid": False,
            "reason": f"Unauthorized table(s) referenced: {sorted(list(unauthorized_tables))}. Only approved tables {sorted(list(ALLOWED_TABLES))} are permitted.",
            "sanitized_sql": None,
            "tables_used": referenced_tables
        }

    # Step 8: Controlled Relational Join Validation
    join_check = validate_join_clauses(clean_sql)
    if not join_check["valid"]:
        return {
            "valid": False,
            "reason": join_check["reason"],
            "sanitized_sql": None,
            "tables_used": referenced_tables
        }

    # Step 9: SQLite Syntax Compilation Check (Dry-Run via EXPLAIN)
    try:
        if db_path:
            conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
        else:
            conn = sqlite3.connect(":memory:")

        with conn:
            cursor = conn.cursor()
            cursor.execute(f"EXPLAIN {clean_sql};")
    except sqlite3.Error as e:
        error_msg = str(e)
        if "no such table" in error_msg.lower() and not db_path:
            pass  # Detached test in-memory connection
        else:
            return {
                "valid": False,
                "reason": f"SQL syntax or execution error: {error_msg}",
                "sanitized_sql": None,
                "tables_used": referenced_tables
            }
    finally:
        if 'conn' in locals():
            conn.close()

    # Sanitized SQL with terminal semicolon
    sanitized_sql = clean_sql + ";"

    return {
        "valid": True,
        "reason": "Query passed all security, schema, relational join, and syntax validations.",
        "sanitized_sql": sanitized_sql,
        "tables_used": referenced_tables
    }
