"""
Talk-to-Data End-to-End Test Suite
==================================
Tests:
1. All 7 required analytical patterns via `answer_question` (offline fallback mode).
2. Business-readable response synthesis for each analytical pattern.
3. Multi-turn conversation context memory via `CreditRiskChatbot`.
4. Guardrail against unsupported questions & hallucination prevention.
5. Guardrail against individual loan underwriting decisions.
6. Malicious SQL generated by simulated rogue LLM (injection / DDL / DML).
7. Malformed LLM JSON response with graceful deterministic fallback.
8. LLM timeout/network error with graceful deterministic fallback.
"""

import os
import sys
from typing import Optional

from src.talk_to_data.chatbot import CreditRiskChatbot, answer_question
from src.talk_to_data.llm import LLMClient
from src.talk_to_data.response_generator import generate_business_response
from src.talk_to_data.sql_generator import generate_sql
from src.talk_to_data.sql_validator import validate_sql


class MockLLMClient(LLMClient):
    """Mock LLM Client for simulating various LLM response conditions."""

    def __init__(self, mock_response: Optional[str] = None, should_raise: bool = False):
        super().__init__()
        self.mock_response = mock_response
        self.should_raise = should_raise

    def is_available(self) -> bool:
        return True

    def complete(self, prompt: str, system_prompt: Optional[str] = None, json_mode: bool = False) -> Optional[str]:
        if self.should_raise:
            raise TimeoutError("Simulated LLM network timeout")
        return self.mock_response


def test_core_analytical_patterns():
    print("\n" + "=" * 80)
    print("1. TESTING ALL 7 CORE ANALYTICAL PATTERNS (OFFLINE FALLBACK MODE)")
    print("=" * 80)

    test_queries = [
        ("Pattern 1 - Overall Portfolio", "What is the overall default rate?"),
        ("Pattern 2 - Education Level", "What is the default rate by education level?"),
        ("Pattern 3 - Income Segmentation", "How does default risk vary by income?"),
        ("Pattern 4 - Prior Refusals", "Do applicants with previous loan refusals have higher default rates?"),
        ("Pattern 5 - Leverage Exposure", "What is the default rate for highly leveraged applicants?"),
        ("Pattern 6 - Late Payment Delinquency", "How does late payment history relate to default risk?"),
        ("Pattern 7 - Organization Risk", "Which organization types have the highest default rates?")
    ]

    for label, question in test_queries:
        res = answer_question(question, use_llm=False)
        print(f"\n[{label}]")
        print(f"Question : \"{question}\"")
        print(f"Success  : {res['success']}")
        print(f"Intent   : {res['intent']}")
        print(f"SQL      : {res['sql']}")
        print(f"Rows     : {res['row_count']}")
        print(f"Answer   : {res['answer']}")

        assert res["success"] is True, f"Failed on {label}"
        assert res["row_count"] > 0, f"Expected non-empty rows for {label}"
        assert len(res["answer"]) > 10, f"Expected readable answer for {label}"
        assert res["used_llm"] is False


def test_conversation_context():
    print("\n" + "=" * 80)
    print("2. TESTING CONVERSATION CONTEXT & MULTI-TURN MEMORY")
    print("=" * 80)

    bot = CreditRiskChatbot(max_history_turns=5, use_llm=False)

    turn1 = bot.ask("What is the default rate by education level?")
    print("Turn 1 Question:", turn1["question"])
    print("Turn 1 SQL     :", turn1["sql"])
    print("Turn 1 Answer  :", turn1["answer"])
    assert turn1["success"] is True

    turn2 = bot.ask("What about only applicants earning above 200000?")
    print("\nTurn 2 Question:", turn2["question"])
    print("Turn 2 SQL     :", turn2["sql"])
    print("Turn 2 Answer  :", turn2["answer"])
    print("Turn 2 Rows    :", turn2["row_count"])
    assert turn2["success"] is True
    assert "amt_income_total > 200000" in turn2["sql"]
    assert len(bot.get_history()) == 2
    print("Status: PASSED (Multi-turn context retained)")


def test_unsupported_questions():
    print("\n" + "=" * 80)
    print("3. TESTING UNSUPPORTED QUESTIONS & HALLUCINATION CONTROL")
    print("=" * 80)

    unsupported = [
        "What was the national unemployment rate last year?",
        "What is the applicant's credit score from Experian?",
        "What is the current inflation rate and GDP growth?"
    ]

    for q in unsupported:
        res = answer_question(q, use_llm=False)
        print(f"\nQuestion : \"{q}\"")
        print(f"Success  : {res['success']}")
        print(f"Intent   : {res['intent']}")
        print(f"Answer   : {res['answer']}")
        assert res["success"] is False
        assert res["intent"] == "unsupported_domain"
        assert "cannot be answered" in res["answer"].lower()
    print("Status: PASSED (Controlled non-hallucination responses)")


def test_individual_underwriting_redirect():
    print("\n" + "=" * 80)
    print("4. TESTING INDIVIDUAL UNDERWRITING SAFETY REDIRECTION")
    print("=" * 80)

    decision_queries = [
        "Should applicant 100001 be approved for a loan?",
        "Should I reject applicant 100002 based on profile?"
    ]

    for q in decision_queries:
        res = answer_question(q, use_llm=False)
        print(f"\nQuestion : \"{q}\"")
        print(f"Success  : {res['success']}")
        print(f"Intent   : {res['intent']}")
        print(f"Answer   : {res['answer']}")
        assert res["success"] is False
        assert res["intent"] == "individual_decision_redirect"
        assert "ml predictor" in res["answer"].lower() or "individual" in res["answer"].lower()
    print("Status: PASSED (Safely redirected to ML predictor)")


def test_malicious_llm_sql_rejection():
    print("\n" + "=" * 80)
    print("5. TESTING MALICIOUS SQL FROM MOCKED ROGUE LLM")
    print("=" * 80)

    # Simulate rogue LLM returning harmful SQL
    malicious_json = '{"intent": "portfolio_analytics", "sql": "SELECT * FROM applicant_analytics; DROP TABLE applicant_analytics;", "reason": "malicious injection"}'
    mock_llm = MockLLMClient(mock_response=malicious_json)

    res = answer_question("What is the overall default rate?", llm_client=mock_llm, use_llm=True)
    print("Simulated Rogue LLM Payload:", malicious_json)
    print("Executed SQL               :", res.get("sql"))
    print("Success                    :", res.get("success"))
    print("Used LLM                   :", res.get("used_llm"))
    print("Answer                     :", res.get("answer"))

    # Even if LLM attempted injection, validation failed and system safely used deterministic fallback
    assert res["success"] is True
    assert "DROP TABLE" not in res["sql"]
    assert res["used_llm"] is False
    print("Status: PASSED (Malicious SQL intercepted and safely neutralized via fallback)")


def test_malformed_llm_json_fallback():
    print("\n" + "=" * 80)
    print("6. TESTING MALFORMED LLM JSON & FALLBACK")
    print("=" * 80)

    malformed_raw = "I am an AI and here is your query: SELECT COUNT(*) FROM applicant_analytics (INVALID JSON)"
    mock_llm = MockLLMClient(mock_response=malformed_raw)

    res = answer_question("What is the default rate by education level?", llm_client=mock_llm, use_llm=True)
    print("Simulated Malformed Output :", malformed_raw)
    print("Fallback Executed SQL      :", res.get("sql"))
    print("Success                    :", res.get("success"))
    print("Answer                     :", res.get("answer"))

    assert res["success"] is True
    assert "name_education_type" in res["sql"]
    assert res["used_llm"] is False
    print("Status: PASSED (Gracefully recovered from malformed LLM response)")


def test_llm_timeout_fallback():
    print("\n" + "=" * 80)
    print("7. TESTING LLM TIMEOUT / NETWORK ERROR FALLBACK")
    print("=" * 80)

    mock_llm = MockLLMClient(should_raise=True)
    res = answer_question("How does default risk vary by income?", llm_client=mock_llm, use_llm=True)
    print("Simulated Timeout Condition: TimeoutError")
    print("Fallback Executed SQL      :", res.get("sql"))
    print("Success                    :", res.get("success"))
    print("Answer                     :", res.get("answer"))

    assert res["success"] is True
    assert "income_tier" in res["sql"]
    assert res["used_llm"] is False
    print("Status: PASSED (Gracefully recovered from LLM timeout without crash)")


def test_top_n_risk_ranking_query_and_narrative():
    print("\n" + "=" * 80)
    print("8. TESTING TOP-N RISK RANKING QUERY & ALIGNED NARRATIVE GENERATION")
    print("=" * 80)

    q = "Show me the top 5 high-risk applicants"
    res = answer_question(q, use_llm=False)
    print(f"Question : \"{q}\"")
    print(f"Success  : {res['success']}")
    print(f"Intent   : {res['intent']}")
    print(f"SQL      : {res['sql']}")
    print(f"Rows     : {res['row_count']}")
    print(f"Answer   : {res['answer']}")

    assert res["success"] is True
    assert res["row_count"] == 5
    assert "applicant_risk_scores" in res["sql"].lower()
    assert "highest" in res["answer"].lower()
    assert "default risk" in res["answer"].lower()
    assert "None applicants" not in res["answer"]
    assert "Secondary / secondary special" not in res["answer"]
    assert "at None" not in res["answer"]
    print("Status: PASSED (Top-5 high-risk narrative precisely aligned with table)")


def run_all_tests():
    test_core_analytical_patterns()
    test_conversation_context()
    test_unsupported_questions()
    test_individual_underwriting_redirect()
    test_malicious_llm_sql_rejection()
    test_malformed_llm_json_fallback()
    test_llm_timeout_fallback()
    test_top_n_risk_ranking_query_and_narrative()
    print("\n" + "=" * 80)
    print("ALL STEP 3C END-TO-END TESTS PASSED SUCCESSFULLY!")
    print("=" * 80)


if __name__ == "__main__":
    run_all_tests()

